import './globals.css'
import Providers from './components/DarkMode/provider' 
import { Montserrat } from 'next/font/google'
const montserrat = Montserrat({ subsets: ['latin'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en" className='dark' style={{colorScheme:'dark'}}>
    
      <body className={montserrat.className}>
      <Providers>
        {children}
        </Providers>
        </body>
      

    </html>
    </>
  )
}
